preferences <- matrix(c(18, 22, 20, 2, 28, 40, 20, 10, 40), ncol = 3, byrow = TRUE)
rownames(preferences) <- c("5-6 years", "7-8 years", "9-10 years")
colnames(preferences) <- c("A", "B", "C")
cov_bc <- cov(preferences[, "B"], preferences[, "C"])
print("Sample Covariance between B and C:")
print(cov_bc)
cov_matrix <- cov(preferences)
print("Sample Covariance Matrix for Preferences:")
print(cov_matrix)
cor_bc <- cor(preferences[, "B"], preferences[, "C"])
print("Sample Correlation between B and C:")
print(cor_bc)
cor_matrix <- cor(preferences)
print("Sample Correlation Matrix for Preferences:")
print(cor_matrix)