data <- c(200, 300, 400, 600, 1000)
min_value <- min(data)
max_value <- max(data)
min_max_normalized_a <- (data - min_value) / (max_value - min_value)
cat("Min-Max Normalization (Method A):\n")
print(min_max_normalized_a)
mean_value <- mean(data)
sd_value <- sd(data)
z_score_normalized <- (data - mean_value) / sd_value
cat("\nZ-Score Normalization:\n")
print(z_score_normalized)